// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void CT003FiltrosdepesquisaDTIDIGITAL() {
    driver.Navigate().GoToUrl("http://www.automationpractice.pl/index.php?id_category=3&controller=category");
    driver.Manage().Window.Size = new System.Drawing.Size(976, 1032);
    driver.FindElement(By.LinkText("In stock (5)")).Click();
    driver.FindElement(By.LinkText("Faded Short Sleeve T-shirts")).Click();
    try {
      Thread.Sleep(css=span > a > span);
    } catch (Exception e) {
      Console.WriteLine("{0} Exception caught.", e);
    }
    {
      WebDriverWait wait = new WebDriverWait(driver, System.TimeSpan.FromSeconds(5));
      wait.Until(driver => driver.FindElement(By.CssSelector("span > a > span")).Displayed);
    }
    driver.FindElement(By.CssSelector("span > a > span")).Click();
    try {
      Thread.Sleep(id=selectProductSort);
    } catch (Exception e) {
      Console.WriteLine("{0} Exception caught.", e);
    }
    driver.FindElement(By.Id("selectProductSort")).Click();
    {
      var dropdown = driver.FindElement(By.Id("selectProductSort"));
      dropdown.FindElement(By.XPath("//option[. = 'In stock']")).Click();
    }
    try {
      Thread.Sleep(css=.ajax_block_product:nth-child(3) .product-name);
    } catch (Exception e) {
      Console.WriteLine("{0} Exception caught.", e);
    }
    driver.FindElement(By.CssSelector(".ajax_block_product:nth-child(3) .product-name")).Click();
  }
}
