// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CT003 - Filtros de pesquisa - DTI DIGITAL', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CT003 - Filtros de pesquisa - DTI DIGITAL', async function() {
    await driver.get("http://www.automationpractice.pl/index.php?id_category=3&controller=category")
    await driver.manage().window().setRect({ width: 976, height: 1032 })
    await driver.findElement(By.linkText("In stock (5)")).click()
    await driver.findElement(By.linkText("Faded Short Sleeve T-shirts")).click()
    await driver.sleep(css=span > a > span)
    await driver.wait(until.elementIsVisible(await driver.findElement(By.css("span > a > span"))), 5000)
    await driver.findElement(By.css("span > a > span")).click()
    await driver.sleep(id=selectProductSort)
    await driver.findElement(By.id("selectProductSort")).click()
    {
      const dropdown = await driver.findElement(By.id("selectProductSort"))
      await dropdown.findElement(By.xpath("//option[. = 'In stock']")).click()
    }
    await driver.sleep(css=.ajax_block_product:nth-child(3) .product-name)
    await driver.findElement(By.css(".ajax_block_product:nth-child(3) .product-name")).click()
  })
})
