// Generated by Selenium IDE in C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void CT001DTIDIGITALCadastro() {
    driver.Navigate().GoToUrl("http://www.automationpractice.pl/index.php");
    driver.Manage().Window.Size = new System.Drawing.Size(976, 1032);
    driver.FindElement(By.LinkText("Sign in")).Click();
    try {
      Thread.Sleep(linikText=Sign in);
    } catch (Exception e) {
      Console.WriteLine("{0} Exception caught.", e);
    }
    {
      WebDriverWait wait = new WebDriverWait(driver, System.TimeSpan.FromSeconds(5));
      wait.Until(driver => driver.FindElement(By.Id("email_create")).Displayed);
    }
    driver.FindElement(By.Id("email_create")).SendKeys("arturfoliv@gmail.com");
    driver.FindElement(By.CssSelector("#SubmitCreate > span")).Click();
    driver.FindElement(By.Id("id_gender1")).Click();
    driver.FindElement(By.Id("customer_firstname")).Click();
    driver.FindElement(By.Id("customer_firstname")).SendKeys("Artur");
    driver.FindElement(By.Id("customer_lastname")).SendKeys("Oliveira");
    driver.FindElement(By.Id("passwd")).Click();
    driver.FindElement(By.Id("passwd")).SendKeys("qwe123");
    driver.FindElement(By.Id("days")).Click();
    {
      var dropdown = driver.FindElement(By.Id("days"));
      dropdown.FindElement(By.XPath("//option[. = 'regexp:19\\s+']")).Click();
    }
    driver.FindElement(By.Id("months")).Click();
    {
      var dropdown = driver.FindElement(By.Id("months"));
      dropdown.FindElement(By.XPath("//option[. = 'regexp:May\\s']")).Click();
    }
    driver.FindElement(By.Id("years")).Click();
    {
      var dropdown = driver.FindElement(By.Id("years"));
      dropdown.FindElement(By.XPath("//option[. = 'regexp:2001\\s+']")).Click();
    }
    driver.FindElement(By.CssSelector("#submitAccount > span")).Click();
  }
}
