// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void CT002AdicionarprodutoaocarrinhoDTIDIGITAL() {
    driver.Navigate().GoToUrl("http://www.automationpractice.pl/index.php");
    driver.Manage().Window.Size = new System.Drawing.Size(976, 1032);
    driver.FindElement(By.Id("search_query_top")).Click();
    driver.FindElement(By.Id("search_query_top")).SendKeys("blouse");
    driver.FindElement(By.Id("search_query_top")).SendKeys(Keys.Enter);
    driver.FindElement(By.CssSelector(".product_img_link > .replace-2x")).Click();
    try {
      Thread.Sleep(id=color_8);
    } catch (Exception e) {
      Console.WriteLine("{0} Exception caught.", e);
    }
    driver.FindElement(By.Id("color_8")).Click();
    driver.FindElement(By.CssSelector(".exclusive > span")).Click();
    driver.FindElement(By.CssSelector(".continue > span")).Click();
  }
}
