// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CT002 - Adicionar produto ao carrinho - DTI DIGITAL', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CT002 - Adicionar produto ao carrinho - DTI DIGITAL', async function() {
    await driver.get("http://www.automationpractice.pl/index.php")
    await driver.manage().window().setRect({ width: 976, height: 1032 })
    await driver.findElement(By.id("search_query_top")).click()
    await driver.findElement(By.id("search_query_top")).sendKeys("blouse")
    await driver.findElement(By.id("search_query_top")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".product_img_link > .replace-2x")).click()
    await driver.sleep(id=color_8)
    await driver.findElement(By.id("color_8")).click()
    await driver.findElement(By.css(".exclusive > span")).click()
    await driver.findElement(By.css(".continue > span")).click()
  })
})
